import { Hono } from 'hono';
import { cors } from 'hono/cors';
import {
  seedRegistry,
  getAllHubTools,
  getHubTool,
  getHubToolVersions,
  incrementInstallCount,
  searchTools,
  getToolsByCategory,
  publishTool,
} from './store';
import type { ToolDetailResponse, ToolListResponse, PublishRequest } from './types';

/* ------------------------------------------------------------------ */
/* App setup                                                           */
/* ------------------------------------------------------------------ */

const app = new Hono();

// Seed the in-memory store on cold start
seedRegistry();

// CORS — allow any Larkup client
app.use('*', cors());

/* ------------------------------------------------------------------ */
/* Health                                                              */
/* ------------------------------------------------------------------ */

app.get('/', (c) => {
  return c.json({
    status: 'ok',
    service: 'larkup-hub',
    version: '0.1.0',
    description: 'Larkup Marketplace Hub API — tool catalog, install tracking, and publishing.',
  });
});

/* ------------------------------------------------------------------ */
/* Tool catalog                                                        */
/* ------------------------------------------------------------------ */

/**
 * GET /v1/tools — List all available tools.
 *
 * Query params:
 *   ?category=media     — Filter by category
 *   ?search=video       — Full-text search
 *   ?page=1&limit=20    — Pagination
 */
app.get('/v1/tools', (c) => {
  const category = c.req.query('category');
  const search = c.req.query('search');
  const page = parseInt(c.req.query('page') ?? '1', 10);
  const limit = Math.min(parseInt(c.req.query('limit') ?? '50', 10), 100);

  let results = category
    ? getToolsByCategory(category)
    : search
    ? searchTools(search)
    : getAllHubTools();

  const total = results.length;
  const offset = (page - 1) * limit;
  results = results.slice(offset, offset + limit);

  const response: ToolListResponse = {
    tools: results.map((t) => ({
      ...t.manifest,
      downloads: (t.manifest.downloads ?? 0) + t.installs,
    })),
    total,
  };

  // Cache catalog responses at edge for 60 seconds
  c.header('Cache-Control', 'public, s-maxage=60, stale-while-revalidate=120');
  return c.json(response);
});

/**
 * GET /v1/tools/:id — Get full tool details.
 */
app.get('/v1/tools/:id', (c) => {
  const toolId = c.req.param('id');
  const tool = getHubTool(toolId);

  if (!tool) {
    return c.json({ error: 'Tool not found' }, 404);
  }

  const toolVersions = getHubToolVersions(toolId);
  const response: ToolDetailResponse = {
    tool: {
      ...tool.manifest,
      downloads: (tool.manifest.downloads ?? 0) + tool.installs,
    },
    installs: tool.installs,
    versions: toolVersions.map((v) => ({
      version: v.version,
      publishedAt: v.publishedAt,
    })),
  };

  c.header('Cache-Control', 'public, s-maxage=60, stale-while-revalidate=120');
  return c.json(response);
});

/* ------------------------------------------------------------------ */
/* Install tracking                                                    */
/* ------------------------------------------------------------------ */

/**
 * POST /v1/tools/:id/installed — Track an install.
 *
 * Called by the marketplace installer after a successful install.
 * Fire-and-forget from the client side.
 */
app.post('/v1/tools/:id/installed', (c) => {
  const toolId = c.req.param('id');
  const count = incrementInstallCount(toolId);

  if (count === 0) {
    return c.json({ error: 'Tool not found' }, 404);
  }

  return c.json({ toolId, installs: count });
});

/* ------------------------------------------------------------------ */
/* curl install script                                                 */
/* ------------------------------------------------------------------ */

/**
 * GET /v1/tools/:id/install.sh — Returns a shell script that installs the tool.
 *
 * Usage: curl -sL hub.larkup.dev/v1/tools/video-audio/install.sh | sh
 */
app.get('/v1/tools/:id/install.sh', (c) => {
  const toolId = c.req.param('id');
  const tool = getHubTool(toolId);

  if (!tool) {
    return c.text('echo "Error: Tool not found"; exit 1', 404);
  }

  const manifest = tool.manifest;
  const script = `#!/bin/sh
# Larkup Marketplace — Install ${manifest.name}
# Generated by hub.larkup.dev
set -e

echo "🚀 Installing ${manifest.name} v${manifest.version}..."
echo ""

# Check system dependencies
${
  manifest.systemDeps?.length
    ? manifest.systemDeps
        .map(
          (dep) => `if ! command -v ${dep} > /dev/null 2>&1; then
  echo "❌ Missing system dependency: ${dep}"
  echo "   Please install ${dep} first."
  exit 1
fi`,
        )
        .join('\n')
    : '# No system dependencies required'
}

# Create tools directory
TOOLS_DIR=".larkup/tools"
mkdir -p "$TOOLS_DIR"

# Initialize package.json if needed
if [ ! -f "$TOOLS_DIR/package.json" ]; then
  echo '{"name":"larkup-tools","version":"1.0.0","private":true}' > "$TOOLS_DIR/package.json"
fi

# Install the tool
echo "📦 Downloading ${manifest.packageName}@${manifest.version}..."
npm install ${manifest.packageName}@${
    manifest.version
  } --prefix "$TOOLS_DIR" --save --no-audit --no-fund

# Record in installed.json
MANIFEST_FILE="$TOOLS_DIR/installed.json"
if [ ! -f "$MANIFEST_FILE" ]; then
  echo '{"tools":[],"downloadCounts":{},"updatedAt":""}' > "$MANIFEST_FILE"
fi

# Update installed.json using node
node -e "
  const fs = require('fs');
  const manifest = JSON.parse(fs.readFileSync('$MANIFEST_FILE', 'utf8'));
  const entry = {
    id: '${manifest.id}',
    version: '${manifest.version}',
    installedAt: new Date().toISOString(),
    packageName: '${manifest.packageName}',
    resolvedPath: '$TOOLS_DIR/node_modules/${manifest.packageName}',
    source: 'registry',
    config: {}
  };
  manifest.tools = manifest.tools.filter(t => t.id !== '${manifest.id}');
  manifest.tools.push(entry);
  manifest.downloadCounts['${manifest.id}'] = (manifest.downloadCounts['${manifest.id}'] || 0) + 1;
  manifest.updatedAt = new Date().toISOString();
  fs.writeFileSync('$MANIFEST_FILE', JSON.stringify(manifest, null, 2));
"

echo ""
echo "✅ ${manifest.name} installed successfully!"
echo "   Version: ${manifest.version}"
echo "   Location: $TOOLS_DIR/node_modules/${manifest.packageName}"
`;

  c.header('Content-Type', 'text/plain; charset=utf-8');
  c.header('Content-Disposition', `inline; filename="install-${toolId}.sh"`);
  return c.text(script);
});

/* ------------------------------------------------------------------ */
/* Publishing (CI webhook)                                             */
/* ------------------------------------------------------------------ */

/**
 * POST /v1/tools/publish — Publish or update a tool.
 *
 * Called by CI after `npm publish`. Protected by API key.
 *
 * Body: { manifest: ToolDescriptor, apiKey?: string }
 */
app.post('/v1/tools/publish', async (c) => {
  try {
    const body = (await c.req.json()) as PublishRequest;

    // API key validation (simple string match for MVP)
    const expectedKey = process.env.HUB_PUBLISH_KEY;
    if (expectedKey && body.apiKey !== expectedKey) {
      return c.json({ error: 'Invalid API key' }, 401);
    }

    if (!body.manifest?.id || !body.manifest?.packageName) {
      return c.json({ error: 'Invalid manifest: id and packageName required' }, 400);
    }

    publishTool(body.manifest);

    return c.json(
      { status: 'published', toolId: body.manifest.id, version: body.manifest.version },
      201,
    );
  } catch (err) {
    return c.json({ error: 'Invalid request body' }, 400);
  }
});

/* ------------------------------------------------------------------ */
/* JSON Schema for tool.manifest.json                                  */
/* ------------------------------------------------------------------ */

app.get('/v1/schema/tool-manifest.v1', (c) => {
  c.header('Cache-Control', 'public, s-maxage=3600');
  return c.json({
    $schema: 'http://json-schema.org/draft-07/schema#',
    title: 'Larkup Tool Manifest',
    description: 'Schema for tool.manifest.json files.',
    type: 'object',
    required: [
      'id',
      'name',
      'description',
      'category',
      'version',
      'pricing',
      'icon',
      'packageName',
      'installSize',
      'author',
      'capabilities',
    ],
    properties: {
      id: { type: 'string', pattern: '^[a-z0-9][a-z0-9-]*[a-z0-9]$' },
      name: { type: 'string' },
      description: { type: 'string' },
      longDescription: { type: 'string' },
      category: {
        type: 'string',
        enum: [
          'media',
          'search',
          'analytics',
          'integration',
          'embedding',
          'ai',
          'automation',
          'utility',
        ],
      },
      version: { type: 'string', pattern: '^\\d+\\.\\d+\\.\\d+' },
      pricing: { type: 'string', enum: ['free', 'pro', 'enterprise'] },
      emoji: { type: 'string' },
      iconUrl: { type: 'string', format: 'uri' },
      icon: { type: 'string' },
      packageName: { type: 'string' },
      installSize: { type: 'string' },
      systemDeps: { type: 'array', items: { type: 'string' } },
      author: { type: 'string' },
      capabilities: { type: 'array', items: { type: 'string' }, minItems: 1 },
      configSchema: { type: 'array' },
      tags: { type: 'array', items: { type: 'string' } },
      downloads: { type: 'number' },
      repositoryUrl: { type: 'string', format: 'uri' },
      license: { type: 'string' },
      updatedAt: { type: 'string' },
      comingSoon: { type: 'boolean' },
    },
  });
});

/* ------------------------------------------------------------------ */
/* Export                                                               */
/* ------------------------------------------------------------------ */

export default app;
