import type {
  ComingSoonIntegrationDefinition,
  IntegrationCatalogEntry,
  IntegrationDefinition,
  IntegrationId,
} from './types.js';

export const atlassianReadScopes = [
  'read:jira-work',
  'read:page:confluence',
  'offline_access',
] as const;

export const readyIntegrations = [
  {
    id: 'notion',
    name: 'Notion',
    category: 'Documentation',
    description: 'Pages, docs, and knowledge bases.',
    icon: '/notion.png',
    status: 'ready',
    oauth: {
      authorizationUrl: 'https://api.notion.com/v1/oauth/authorize',
      tokenUrl: 'https://api.notion.com/v1/oauth/token',
      scopes: [],
      clientIdEnv: 'NOTION_CLIENT_ID',
      clientSecretEnv: 'NOTION_CLIENT_SECRET',
      accessTokenEnv: 'NOTION_ACCESS_TOKEN',
      clientAuthentication: 'basic',
    },
  },
  {
    id: 'google-analytics',
    name: 'Google Analytics',
    category: 'Analytics',
    description: 'Traffic and content reports.',
    icon: '/icons/google-analytics.png',
    status: 'ready',
    oauth: {
      authorizationUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
      tokenUrl: 'https://oauth2.googleapis.com/token',
      scopes: ['https://www.googleapis.com/auth/analytics.readonly'],
      clientIdEnv: 'GOOGLE_CLIENT_ID',
      clientSecretEnv: 'GOOGLE_CLIENT_SECRET',
      accessTokenEnv: 'GOOGLE_ANALYTICS_ACCESS_TOKEN',
      clientAuthentication: 'body',
      authorizationParams: { access_type: 'offline', prompt: 'consent' },
    },
  },
  {
    id: 'google-calendar',
    name: 'Google Calendar',
    category: 'Scheduling',
    description: 'Calendar events and meetings.',
    icon: '/icons/google-calender.png',
    status: 'ready',
    oauth: {
      authorizationUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
      tokenUrl: 'https://oauth2.googleapis.com/token',
      scopes: ['https://www.googleapis.com/auth/calendar.events.readonly'],
      clientIdEnv: 'GOOGLE_CLIENT_ID',
      clientSecretEnv: 'GOOGLE_CLIENT_SECRET',
      accessTokenEnv: 'GOOGLE_CALENDAR_ACCESS_TOKEN',
      clientAuthentication: 'body',
      authorizationParams: { access_type: 'offline', prompt: 'consent' },
    },
  },
  {
    id: 'google-docs',
    name: 'Google Docs',
    category: 'Documentation',
    description: 'Documents and shared content.',
    icon: '/icons/google-docs.png',
    status: 'ready',
    oauth: {
      authorizationUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
      tokenUrl: 'https://oauth2.googleapis.com/token',
      scopes: [
        'https://www.googleapis.com/auth/documents.readonly',
        'https://www.googleapis.com/auth/drive.readonly',
      ],
      clientIdEnv: 'GOOGLE_CLIENT_ID',
      clientSecretEnv: 'GOOGLE_CLIENT_SECRET',
      accessTokenEnv: 'GOOGLE_DOCS_ACCESS_TOKEN',
      clientAuthentication: 'body',
      authorizationParams: { access_type: 'offline', prompt: 'consent' },
    },
  },
  {
    id: 'google-drive',
    name: 'Google Drive',
    category: 'Documentation',
    description: 'Files and shared-drive knowledge.',
    icon: '/icons/google-drive.png',
    status: 'ready',
    oauth: {
      authorizationUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
      tokenUrl: 'https://oauth2.googleapis.com/token',
      scopes: ['https://www.googleapis.com/auth/drive.readonly'],
      clientIdEnv: 'GOOGLE_CLIENT_ID',
      clientSecretEnv: 'GOOGLE_CLIENT_SECRET',
      accessTokenEnv: 'GOOGLE_DRIVE_ACCESS_TOKEN',
      clientAuthentication: 'body',
      authorizationParams: { access_type: 'offline', prompt: 'consent' },
    },
  },
  {
    id: 'google-maps',
    name: 'Google Maps',
    category: 'Location',
    description: 'Your Google My Maps and their details.',
    icon: '/icons/google-maps.png',
    status: 'ready',
    oauth: {
      authorizationUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
      tokenUrl: 'https://oauth2.googleapis.com/token',
      scopes: ['https://www.googleapis.com/auth/drive.readonly'],
      clientIdEnv: 'GOOGLE_CLIENT_ID',
      clientSecretEnv: 'GOOGLE_CLIENT_SECRET',
      accessTokenEnv: 'GOOGLE_MAPS_ACCESS_TOKEN',
      clientAuthentication: 'body',
      authorizationParams: { access_type: 'offline', prompt: 'consent' },
    },
  },
  {
    id: 'google-meet',
    name: 'Google Meet',
    category: 'Communication',
    description: 'Meeting records you organized.',
    icon: '/icons/google-meet.png',
    status: 'ready',
    oauth: {
      authorizationUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
      tokenUrl: 'https://oauth2.googleapis.com/token',
      scopes: ['https://www.googleapis.com/auth/meetings.space.readonly'],
      clientIdEnv: 'GOOGLE_CLIENT_ID',
      clientSecretEnv: 'GOOGLE_CLIENT_SECRET',
      accessTokenEnv: 'GOOGLE_MEET_ACCESS_TOKEN',
      clientAuthentication: 'body',
      authorizationParams: { access_type: 'offline', prompt: 'consent' },
    },
  },
  {
    id: 'google-sheets',
    name: 'Google Sheets',
    category: 'Spreadsheets',
    description: 'Sheets and table data.',
    icon: '/icons/google-sheets.png',
    status: 'ready',
    oauth: {
      authorizationUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
      tokenUrl: 'https://oauth2.googleapis.com/token',
      scopes: [
        'https://www.googleapis.com/auth/spreadsheets.readonly',
        'https://www.googleapis.com/auth/drive.readonly',
      ],
      clientIdEnv: 'GOOGLE_CLIENT_ID',
      clientSecretEnv: 'GOOGLE_CLIENT_SECRET',
      accessTokenEnv: 'GOOGLE_SHEETS_ACCESS_TOKEN',
      clientAuthentication: 'body',
      authorizationParams: { access_type: 'offline', prompt: 'consent' },
    },
  },
  {
    id: 'google-slides',
    name: 'Google Slides',
    category: 'Documentation',
    description: 'Presentation content.',
    icon: '/icons/google-slides.png',
    status: 'ready',
    oauth: {
      authorizationUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
      tokenUrl: 'https://oauth2.googleapis.com/token',
      scopes: [
        'https://www.googleapis.com/auth/presentations.readonly',
        'https://www.googleapis.com/auth/drive.readonly',
      ],
      clientIdEnv: 'GOOGLE_CLIENT_ID',
      clientSecretEnv: 'GOOGLE_CLIENT_SECRET',
      accessTokenEnv: 'GOOGLE_SLIDES_ACCESS_TOKEN',
      clientAuthentication: 'body',
      authorizationParams: { access_type: 'offline', prompt: 'consent' },
    },
  },
  {
    id: 'slack',
    name: 'Slack',
    category: 'Communication',
    description: 'Public channels and their messages.',
    icon: '/icons/slack.png',
    status: 'ready',
    oauth: {
      authorizationUrl: 'https://slack.com/oauth/v2/authorize',
      tokenUrl: 'https://slack.com/api/oauth.v2.access',
      scopes: ['channels:read', 'channels:history', 'groups:read', 'groups:history'],
      clientIdEnv: 'SLACK_CLIENT_ID',
      clientSecretEnv: 'SLACK_CLIENT_SECRET',
      accessTokenEnv: 'SLACK_ACCESS_TOKEN',
      clientAuthentication: 'body',
    },
  },
  {
    id: 'github',
    name: 'GitHub',
    category: 'Engineering',
    description: 'Repositories and README knowledge.',
    icon: '/github.svg',
    status: 'ready',
    oauth: {
      authorizationUrl: 'https://github.com/login/oauth/authorize',
      tokenUrl: 'https://github.com/login/oauth/access_token',
      scopes: ['read:user', 'repo'],
      clientIdEnv: 'GITHUB_CLIENT_ID',
      clientSecretEnv: 'GITHUB_CLIENT_SECRET',
      accessTokenEnv: 'GITHUB_ACCESS_TOKEN',
      clientAuthentication: 'body',
    },
  },
  {
    id: 'jira',
    name: 'Jira',
    category: 'Project management',
    description: 'Issues, projects, and releases.',
    icon: '/icons/jira.png',
    status: 'ready',
    oauth: {
      authorizationUrl: 'https://auth.atlassian.com/authorize',
      tokenUrl: 'https://auth.atlassian.com/oauth/token',
      scopes: [...atlassianReadScopes],
      clientIdEnv: 'ATLASSIAN_CLIENT_ID',
      clientSecretEnv: 'ATLASSIAN_CLIENT_SECRET',
      accessTokenEnv: 'JIRA_ACCESS_TOKEN',
      clientAuthentication: 'body',
      authorizationParams: { audience: 'api.atlassian.com', prompt: 'consent' },
    },
  },
  {
    id: 'linear',
    name: 'Linear',
    category: 'Project management',
    description: 'Issues, projects, and roadmaps.',
    icon: '/icons/linear.png',
    status: 'ready',
    oauth: {
      authorizationUrl: 'https://linear.app/oauth/authorize',
      tokenUrl: 'https://api.linear.app/oauth/token',
      scopes: ['read'],
      clientIdEnv: 'LINEAR_CLIENT_ID',
      clientSecretEnv: 'LINEAR_CLIENT_SECRET',
      accessTokenEnv: 'LINEAR_ACCESS_TOKEN',
      clientAuthentication: 'body',
    },
  },
  {
    id: 'confluence',
    name: 'Confluence',
    category: 'Documentation',
    description: 'Pages and team knowledge spaces.',
    icon: '/icons/Confluence.png',
    status: 'ready',
    oauth: {
      authorizationUrl: 'https://auth.atlassian.com/authorize',
      tokenUrl: 'https://auth.atlassian.com/oauth/token',
      scopes: [...atlassianReadScopes],
      clientIdEnv: 'ATLASSIAN_CLIENT_ID',
      clientSecretEnv: 'ATLASSIAN_CLIENT_SECRET',
      accessTokenEnv: 'CONFLUENCE_ACCESS_TOKEN',
      clientAuthentication: 'body',
      authorizationParams: { audience: 'api.atlassian.com', prompt: 'consent' },
    },
  },
] as const satisfies readonly IntegrationDefinition[];

export const pendingVerificationIntegrationIds = [
  'google-analytics',
  'google-calendar',
  'google-docs',
  'google-drive',
  'google-maps',
  'google-meet',
  'google-sheets',
  'google-slides',
] as const;

const pendingVerificationIntegrationIdSet = new Set<string>(pendingVerificationIntegrationIds);

export const comingSoonIntegrations = [
  ['airtable', 'Airtable', 'Databases', 'Bases and workspace records.', 'airtable.png'],
  ['asana', 'Asana', 'Project management', 'Projects, tasks, and goals.', 'asana.png'],
  ['ashby', 'Ashby', 'Recruiting', 'Candidates and interview data.', 'ashby.png'],
  ['aws-kendra', 'AWS Kendra', 'Search', 'Enterprise knowledge-base results.', 'aws-kendra.png'],
  [
    'azure-ai-search',
    'Azure AI Search',
    'Search',
    'Indexed enterprise documents.',
    'azure-ai-search.png',
  ],
  ['bigquery', 'BigQuery', 'Analytics', 'Datasets and query results.', 'bigquery.png'],
  ['bitbucket', 'Bitbucket', 'Engineering', 'Repositories and pull requests.', 'bitbucket.png'],
  ['calendly', 'Calendly', 'Scheduling', 'Events and availability.', 'calendly.png'],
  ['databricks', 'Databricks', 'Analytics', 'Unity Catalog and SQL results.', 'databricks.png'],
  ['deepl', 'DeepL', 'Language', 'Translated documents and glossaries.', 'deepl.png'],
  ['elevenlabs', 'ElevenLabs', 'Media', 'Transcripts and audio content.', 'elevenlabs.png'],
  ['excel', 'Excel', 'Spreadsheets', 'Workbook sheets and cells.', 'excel.png'],
  ['gmail', 'Gmail', 'Communication', 'Email search and threads.', 'gmail.png'],
  ['google-tasks', 'Google Tasks', 'Productivity', 'Task lists and tasks.', 'google-tasks.png'],
  ['hubspot', 'HubSpot', 'CRM', 'Contacts, companies, and deals.', 'hubspot.png'],
  ['looker', 'Looker', 'Analytics', 'Models, Looks, and dashboards.', 'looker.png'],
  ['looker-api-key', 'Looker API-Key', 'Analytics', 'Looker API-key connection.', 'looker.png'],
  ['luma', 'Luma', 'Events', 'Events and guest information.', 'luma.png'],
  ['microsoft-entra', 'Microsoft Entra', 'Directory', 'Users and groups.', 'microsoft-intra.png'],
  [
    'microsoft-onenote',
    'Microsoft OneNote',
    'Documentation',
    'Notebooks and pages.',
    'microsoft-onenote.png',
  ],
  [
    'microsoft-planner',
    'Microsoft Planner',
    'Productivity',
    'Plans, buckets, and tasks.',
    'microsoft-planner.png',
  ],
  [
    'microsoft-teams',
    'Microsoft Teams',
    'Communication',
    'Chats, channels, and transcripts.',
    'microsoft-teams.png',
  ],
  ['miro', 'Miro', 'Collaboration', 'Boards, cards, and sticky notes.', 'miro.png'],
  ['onedrive', 'OneDrive', 'Documentation', 'Files and folders.', 'onedrive.png'],
  [
    'outlook-calendar',
    'Outlook Calendar',
    'Scheduling',
    'Calendar events and availability.',
    'outlook-calendar.png',
  ],
  [
    'outlook-email',
    'Outlook Email',
    'Communication',
    'Mailbox search and threads.',
    'outlook-email.png',
  ],
  ['personio', 'Personio', 'HR', 'Employees and attendance.', 'personio.png'],
  ['pinecone', 'Pinecone', 'Vector database', 'Namespaces and vector records.', 'pinecone.png'],
  ['pipedrive', 'Pipedrive', 'CRM', 'Deals, contacts, and activities.', 'pipedrive.png'],
  ['power-bi', 'Power BI', 'Analytics', 'Datasets, reports, and dashboards.', 'power-pi.png'],
  ['pylon', 'Pylon', 'Support', 'Tickets and knowledge-base articles.', 'pylon.png'],
  ['salesforce', 'Salesforce', 'CRM', 'Accounts, contacts, and opportunities.', 'salesforce.png'],
  ['servicenow', 'ServiceNow', 'Support', 'Incidents, tasks, and configuration.', 'servicenow.png'],
  [
    'sharepoint',
    'SharePoint',
    'Documentation',
    'Sites, lists, and document libraries.',
    'sharepoint.png',
  ],
  ['snowflake', 'Snowflake', 'Analytics', 'Data warehouse queries and schema.', 'snowflake.png'],
  ['snowflake-pat', 'Snowflake PAT', 'Analytics', 'Token-based Snowflake access.', 'snowflake.png'],
  ['statista', 'Statista', 'Research', 'Statistics and market data.', 'statistia.png'],
  ['stripe', 'Stripe', 'Payments', 'Customers, invoices, and payments.', 'stripe.png'],
  ['tableau', 'Tableau', 'Analytics', 'Workbooks and dashboards.', 'tableau.png'],
  [
    'vertex-ai-vector-search',
    'Vertex AI Vector Search',
    'Vector database',
    'Vector-index similarity search.',
    'vertex-ai.png',
  ],
  ['zendesk', 'Zendesk', 'Support', 'Tickets and help-center articles.', 'zendesk.png'],
  ['zoom', 'Zoom', 'Communication', 'Past meetings and meeting details.', 'zoom.png'],
].map(([id, name, category, description, icon]) => ({
  id,
  name,
  category,
  description,
  icon: icon.startsWith('/') ? icon : `/icons/${icon}`,
  status: 'coming-soon' as const,
})) satisfies readonly ComingSoonIntegrationDefinition[];

/** Google sources lead the catalog, followed by Microsoft sources, then the rest. */
function catalogOrder(left: IntegrationCatalogEntry, right: IntegrationCatalogEntry): number {
  const group = (id: string) =>
    id.startsWith('google-') ? 0 : id.startsWith('microsoft-') ? 1 : 2;
  return group(left.id) - group(right.id) || left.name.localeCompare(right.name);
}

export const integrations = [
  ...readyIntegrations.map((integration): IntegrationCatalogEntry => {
    if (!pendingVerificationIntegrationIdSet.has(integration.id)) return integration;
    const { oauth: _oauth, ...metadata } = integration;
    return { ...metadata, status: 'coming-soon' };
  }),
  ...comingSoonIntegrations,
].sort(catalogOrder) as readonly IntegrationCatalogEntry[];

export function getIntegration(id: string): IntegrationDefinition | undefined {
  return readyIntegrations.find((integration) => integration.id === id) as
    | IntegrationDefinition
    | undefined;
}

export function isIntegrationId(id: string): id is IntegrationId {
  return Boolean(getIntegration(id));
}
