/** Built-in Marketplace tool manifests. */
export const BUILTIN_TOOLS: Record<string, unknown>[] = [
  {
    manifestVersion: '3.0',
    kind: 'tool',
    id: 'video-intelligence',
    name: 'Video Intelligence (New)',
    description:
      'Index videos locally or in a quota-controlled cloud runtime with speech, OCR, objects, and timestamped evidence.',
    longDescription:
      'A removable marketplace extension with a lightweight TypeScript client and one portable Docker runtime. Users can select local Docker, Larkup Cloud, or their own compatible endpoint.',
    category: 'media',
    version: '0.1.0',
    pricing: 'free',
    emoji: '🎬',
    icon: 'Film',
    packageName: '@larkup/tool-video-intelligence',
    installSize: '~120 KB client; ~8 GB optional runtime image',
    systemDeps: ['docker'],
    requiresSandbox: true,
    author: 'Larkup',
    capabilities: [
      'video-indexing',
      'video-indexing-brief',
      'full-frame-coverage',
      'local-video-runtime',
      'cloud-video-runtime',
      'timestamped-transcription',
      'ocr',
      'object-detection',
      'anonymous-object-tracking',
      'usage-metering',
    ],
    entrypoints: { server: '.', agent: '.', ui: './ui' },
    runtime: {
      protocolVersion: '1',
      defaultMode: 'managed-cloud',
      healthPath: '/v1/health',
      modes: [
        {
          id: 'local-docker',
          label: 'Local Docker',
          description: 'Keep source media and evidence on this computer.',
          image: 'ghcr.io/larkup-ai/video-intelligence:0.1.0',
          composeFile: 'compose.yaml',
          requiresGpu: false,
        },
        {
          id: 'managed-cloud',
          label: 'Larkup Cloud',
          description: 'Use metered GPU workers in the configured EU region.',
          endpointConfigKey: 'cloudEndpoint',
          credentialConfigKey: 'cloudApiKey',
          requiresGpu: true,
        },
        {
          id: 'custom-remote',
          label: 'Custom endpoint',
          description: 'Use your own deployment of the same runtime protocol.',
          endpointConfigKey: 'cloudEndpoint',
          credentialConfigKey: 'cloudApiKey',
          requiresGpu: false,
        },
      ],
    },
    billing: {
      model: 'hybrid',
      entitlementVersion: '1',
      meters: [
        { id: 'source-minute', unit: 'minute', description: 'Minutes of source video.' },
        { id: 'deep-inspection-minute', unit: 'minute', description: 'Deep video minutes.' },
        { id: 'gpu-second', unit: 'second', description: 'GPU worker seconds.' },
        { id: 'ocr-frame', unit: 'frame', description: 'Frames processed by OCR.' },
      ],
    },
    ui: {
      isolation: 'sandboxed-iframe',
      surfaces: [
        {
          id: 'video-indexing-brief',
          slot: 'data-indexing',
          title: 'Guide video indexing',
          entrypoint: './ui',
        },
        {
          id: 'video-evidence-result',
          slot: 'chat-result',
          title: 'Video evidence',
          entrypoint: './ui',
        },
      ],
    },
    tags: ['video', 'ocr', 'tracking', 'local', 'gpu', 'aws', 'gdpr'],
    downloads: 0,
    repositoryUrl: 'https://github.com/Larkup-AI/larkup',
    license: 'Apache-2.0',
    updatedAt: '2026-08-20',
    trustLevel: 'elevated',
    permissions: {
      fsRead: true,
      fsWrite: true,
      exec: true,
      httpAllow: ['127.0.0.1', 'localhost', 'video.larkup.de'],
    },
    configSchema: [
      {
        key: 'runtimeMode',
        label: 'Runtime',
        type: 'select',
        group: 'Compute',
        defaultValue: 'managed-cloud',
        options: [
          { label: 'Local Docker', value: 'local-docker' },
          { label: 'Larkup Cloud', value: 'managed-cloud' },
          { label: 'Custom endpoint', value: 'custom-remote' },
        ],
      },
      {
        key: 'localEndpoint',
        label: 'Local endpoint',
        type: 'text',
        group: 'Compute',
        defaultValue: 'http://127.0.0.1:8787',
      },
      {
        key: 'cloudEndpoint',
        label: 'Cloud endpoint',
        type: 'text',
        group: 'Compute',
      },
      {
        key: 'cloudApiKey',
        label: 'Cloud API key',
        type: 'password',
        group: 'Compute',
      },
    ],
  },
  {
    id: 'video-audio',
    name: 'Video Intelligence',
    description:
      'Build evidence-backed video timelines with adaptive attention and bounded source rewind.',
    longDescription:
      'Evidence-first video reasoning for your knowledge base. ' +
      'Creates multilingual transcripts, activity-aware visual/OCR evidence, timestamped source ranges, ' +
      'and bounded rewind for complex questions. Supports YouTube URLs, ' +
      'direct file upload, and bulk processing. Includes ffmpeg automatically and prepares the YouTube downloader on first use.',
    category: 'media',
    version: '0.3.6',
    pricing: 'free',
    emoji: '🎬',
    icon: 'Film',
    packageName: '@larkup/tool-video-audio',
    installSize: '~15 MB',
    requiresSandbox: true,
    author: 'Larkup',
    capabilities: [
      'video-indexing',
      'audio-indexing',
      'transcription',
      'frame-extraction',
      'youtube-import',
      'attention-driven-analysis',
      'temporal-evidence',
      'bounded-source-rewind',
    ],
    tags: ['video intelligence', 'temporal reasoning', 'transcription', 'ffmpeg', 'video', 'audio'],
    repositoryUrl: 'https://github.com/Larkup-AI/larkup',
    license: 'Apache-2.0',
    updatedAt: '2026-07-20',
    configSchema: [
      {
        key: 'frameInterval',
        label: 'Baseline coverage interval (seconds)',
        type: 'text',
        defaultValue: '10',
        help: 'Baseline cadence for duration-aware coverage frames; scene changes and a reserved ending pass are added separately.',
      },
      {
        key: 'audioProvider',
        label: 'Audio Provider',
        type: 'select',
        help: 'Choose the provider used only for audio and video transcription.',
        options: [
          { label: 'OpenAI', value: 'openai' },
          { label: 'Groq', value: 'groq' },
          { label: 'Deepgram', value: 'deepgram' },
          { label: 'ElevenLabs', value: 'elevenlabs' },
          { label: 'Local Whisper', value: 'local' },
        ],
      },
      {
        key: 'audioLanguage',
        label: 'Transcription language',
        type: 'text',
        defaultValue: 'auto',
        help: 'Use auto for provider language detection, or enter a language code such as ar, ar-EG, en, or de to override it.',
      },
      {
        key: 'audioApiKey',
        label: 'Audio API Key',
        type: 'password',
        help: 'Required for the selected audio provider and kept separate from the chat model key.',
      },
    ],
  },
  {
    id: 'clip-embeddings',
    name: 'CLIP Image Search',
    description: 'Direct image-to-image similarity search using CLIP/SigLIP embeddings.',
    longDescription:
      'Enable native visual similarity search by embedding images with CLIP or SigLIP models. ' +
      "Search your image library by uploading a query image or describing what you're looking for. " +
      'Requires downloading a ~200MB model on first use.',
    category: 'embedding',
    version: '0.1.0',
    pricing: 'free',
    emoji: '🔍',
    icon: 'ScanEye',
    packageName: '@larkup/tool-clip-embeddings',
    installSize: '~200 MB',
    author: 'Larkup',
    capabilities: ['clip-embeddings', 'image-similarity'],
    tags: ['clip', 'siglip', 'image-search', 'visual-similarity'],
    repositoryUrl: 'https://github.com/Larkup-AI/larkup',
    license: 'Apache-2.0',
    updatedAt: '2026-07-20',
    comingSoon: true,
  },
  {
    id: 'doc-editor',
    name: 'Document Editor',
    description: 'AI-powered form filling and document editing with Canvas-style live preview.',
    longDescription:
      'Open PDF, Word, PowerPoint, and text files in a split-view Canvas. ' +
      'AI fills forms using your knowledge base, edits content on request, and previews changes live. ' +
      'Supports PDF form fields (AcroForm), DOCX paragraphs/tables, PPTX slide text, and plain text editing. ' +
      'Uses pdf-lib (native) for PDF and the Docker sandbox for DOCX/PPTX via python-docx/python-pptx.',
    category: 'utility',
    version: '0.2.3',
    pricing: 'free',
    emoji: '📝',
    icon: 'FileEdit',
    packageName: '@larkup/tool-doc-editor',
    installSize: '~5 MB',
    systemDeps: ['docker'],
    requiresSandbox: true,
    author: 'Larkup',
    capabilities: ['document-editing', 'form-filling', 'document-preview'],
    tags: ['pdf', 'docx', 'pptx', 'form', 'canvas', 'editor', 'fill'],
    repositoryUrl: 'https://github.com/Larkup-AI/larkup',
    license: 'Apache-2.0',
    updatedAt: '2026-07-20',
  },
];
