/** Built-in Marketplace tool manifests. */
export const BUILTIN_TOOLS: Record<string, unknown>[] = [
  {
    manifestVersion: '3.0',
    kind: 'tool',
    id: 'video-intelligence',
    name: 'Video Intelligence',
    description:
      'Help your AI understand your videos, so you can ask questions and get answers from the right moments.',
    longDescription:
      'Turn videos into knowledge your AI can understand. It listens to what is said, reads what appears on screen, and helps you find the moments that matter.',
    category: 'media',
    version: '0.1.0',
    pricing: 'free',
    emoji: '🎬',
    icon: 'Film',
    packageName: '@larkup/tool-video-intelligence',
    installSize: '~120 KB',
    requiresSandbox: false,
    author: 'Larkup',
    capabilities: [
      'video-indexing',
      'video-indexing-brief',
      'agentic-video-indexing',
      'cloud-video-runtime',
      'timestamped-transcription',
      'ocr',
      'object-detection',
      'anonymous-object-tracking',
      'usage-metering',
    ],
    entrypoints: { server: '.', agent: '.', ui: './ui' },
    runtime: {
      protocolVersion: '1',
      defaultMode: 'managed-cloud',
      healthPath: '/v1/health',
      modes: [
        {
          id: 'managed-cloud',
          label: 'Larkup Cloud',
          description: 'Index with managed private GPU capacity and your Larkup Cloud allowance.',
          requiresGpu: true,
        },
        {
          id: 'local',
          label: 'Local runtime',
          icon: '/docker.png',
          description: 'Run the application locally on your computer.',
          endpointConfigKey: 'localRuntimeUrl',
          credentialConfigKey: 'localRuntimeApiKey',
          image: 'ghcr.io/larkup-ai/video-intelligence:0.1.0',
          composeFile: 'compose.yaml',
          setupNotice:
            'The local application and its models download to this computer. The initial download can be large.',
        },
        {
          id: 'custom-remote',
          label: 'Custom runtime',
          description: 'Connect a compatible Video Intelligence deployment you operate.',
          endpointConfigKey: 'customRuntimeUrl',
          credentialConfigKey: 'customRuntimeApiKey',
          requiresGpu: true,
        },
      ],
    },
    billing: {
      model: 'hybrid',
      entitlementVersion: '1',
      meters: [
        { id: 'source-minute', unit: 'minute', description: 'Minutes of source video.' },
        {
          id: 'thorough-inspection-minute',
          unit: 'minute',
          description: 'Minutes inspected with Thorough agent coverage.',
        },
        { id: 'gpu-second', unit: 'second', description: 'GPU worker seconds.' },
        { id: 'ocr-frame', unit: 'frame', description: 'Frames processed by OCR.' },
      ],
    },
    usage: {
      label: 'Usage this month',
      visibleWhenRuntimeMode: ['managed-cloud'],
      visualization: { usedKey: 'sourceMinutesUsed', limitKey: 'sourceMinutesLimit' },
      support: {
        contactLabel: 'Request more usage',
        description:
          'Each installation receives Cloud access automatically. Request more video-processing usage when your allowance is low.',
        userIdConfigKey: 'cloudInstallationId',
      },
      fields: [
        { key: 'sourceMinutesUsed', label: 'Used', format: 'minutes' },
        { key: 'sourceMinutesLimit', label: 'Included', format: 'minutes' },
        { key: 'activeJobs', label: 'Active jobs', format: 'number' },
      ],
    },
    ui: {
      isolation: 'sandboxed-iframe',
      surfaces: [
        {
          id: 'video-indexing-brief',
          slot: 'data-indexing',
          title: 'Let your AI understand this video',
          entrypoint: './ui',
          appliesTo: ['video'],
          description:
            'Choose how deeply to analyze it and optionally point it to what matters most.',
          estimate: {
            modeField: 'indexingMode',
            variants: [
              {
                value: 'fast',
                analyzedFramesPerSourceMinute: 5,
                ocrFramesPerSourceMinute: 3,
                processingSecondsPerSourceMinute: 8,
                maxProcessingSecondsPerSourceMinute: 15,
                fixedOverheadSeconds: 90,
                maxFixedOverheadSeconds: 180,
                creditsPerSourceMinute: 1,
              },
              {
                value: 'balanced',
                analyzedFramesPerSourceMinute: 12,
                ocrFramesPerSourceMinute: 8,
                processingSecondsPerSourceMinute: 16,
                maxProcessingSecondsPerSourceMinute: 30,
                fixedOverheadSeconds: 120,
                maxFixedOverheadSeconds: 240,
                creditsPerSourceMinute: 2,
              },
              {
                value: 'thorough',
                analyzedFramesPerSourceMinute: 30,
                ocrFramesPerSourceMinute: 20,
                processingSecondsPerSourceMinute: 32,
                maxProcessingSecondsPerSourceMinute: 60,
                fixedOverheadSeconds: 180,
                maxFixedOverheadSeconds: 360,
                creditsPerSourceMinute: 4,
              },
            ],
          },
          form: {
            submitLabel: 'Start indexing',
            fields: [
              {
                key: 'goal',
                type: 'textarea',
                label: 'What should your AI look for? (optional)',
                placeholder:
                  'For example: find the final score, the moment the package is dropped, or every mention of pricing.',
              },
              {
                key: 'indexingMode',
                type: 'select',
                label: 'Coverage',
                defaultValue: 'balanced',
                options: [
                  {
                    label: 'Fast',
                    value: 'fast',
                    description: 'Sample key frames for a quick overview.',
                    setValues: { processingAuthorityConfirmed: false },
                  },
                  {
                    label: 'Balanced',
                    value: 'balanced',
                    description: 'Sample visual and OCR evidence across the video.',
                    setValues: { processingAuthorityConfirmed: false },
                  },
                  {
                    label: 'Thorough',
                    value: 'thorough',
                    description:
                      'Let the agent inspect denser evidence around subtle or infrequent details.',
                    setValues: { processingAuthorityConfirmed: false },
                  },
                ],
              },
            ],
          },
        },
        {
          id: 'video-evidence-result',
          slot: 'chat-result',
          title: 'Video evidence',
          entrypoint: './ui',
        },
      ],
    },
    tags: ['video', 'ocr', 'tracking', 'local', 'gpu', 'private', 'gdpr'],
    downloads: 0,
    repositoryUrl: 'https://github.com/Larkup-AI/larkup',
    license: 'Apache-2.0',
    updatedAt: '2026-08-20',
    trustLevel: 'elevated',
    permissions: {
      fsRead: true,
      fsWrite: true,
      exec: true,
      httpAllow: ['127.0.0.1', 'localhost', 'video.larkup.de'],
    },
    configSchema: [
      {
        key: 'runtimeMode',
        label: 'Runtime',
        type: 'select',
        group: 'Runtime',
        defaultValue: 'managed-cloud',
        help: 'Choose managed Larkup Cloud, a local runtime that auto-selects Docker or native, or your compatible deployment.',
        options: [
          {
            label: 'Larkup Cloud',
            value: 'managed-cloud',
            icon: '/logo.png',
            description: 'Managed GPU capacity and automatic device access.',
          },
          {
            label: 'Local runtime',
            value: 'local',
            icon: '/docker.png',
            description: 'Run the application locally on your computer.',
          },
          {
            label: 'Custom runtime',
            value: 'custom-remote',
            icon: '/icons/cloudflare.png',
            description: 'Use your deployment URL and key.',
          },
        ],
      },
      {
        key: 'localRuntimeUrl',
        label: 'Local runtime URL',
        type: 'text',
        group: 'Local runtime',
        defaultValue: 'http://127.0.0.1:8787',
        help: 'Use a LAN address to share the runtime with trusted users.',
        verification: {
          endpoint: '/api/tools/video-intelligence/verify',
          method: 'POST',
          fields: {
            localRuntimeUrl: 'localRuntimeUrl',
            localRuntimeApiKey: 'localRuntimeApiKey',
            runtimeMode: 'runtimeMode',
          },
        },
        visibleWhen: { field: 'runtimeMode', equals: 'local' },
      },
      {
        key: 'localRuntimeApiKey',
        label: 'Shared local API key',
        type: 'password',
        group: 'Local runtime',
        help: 'Optional bearer key when local runtime authentication is enabled.',
        visibleWhen: { field: 'runtimeMode', equals: 'local' },
      },
      {
        key: 'videoVisionProvider',
        label: 'Vision provider',
        type: 'select',
        group: 'Video understanding',
        defaultValue: 'vercel_ai_gateway',
        defaultFromGlobalConfigKey: 'visionProvider',
        help: 'Required for every runtime. Starts with your saved AI Models provider; Larkup Cloud supplies GPU compute, not model credits.',
        options: [
          {
            label: 'Google Gemini',
            value: 'google',
            icon: '/icons/gemini.svg',
            description: 'Use Gemini directly with a Google API key.',
          },
          {
            label: 'Vercel AI Gateway',
            value: 'vercel_ai_gateway',
            icon: '/icons/vercel.svg',
            description: 'Use a Gateway model and key.',
          },
          {
            label: 'OpenAI',
            value: 'openai',
            icon: '/icons/openai.svg',
            description: 'Use an OpenAI vision model directly.',
          },
        ],
      },
      {
        key: 'videoVisionApiKey',
        label: 'Vision provider API key',
        type: 'password',
        group: 'Video understanding',
        help: 'Required unless this provider key is already saved in AI Models. It stays in this installation and is forwarded only for the active job.',
        verification: {
          endpoint: '/api/tools/video-intelligence/verify',
          method: 'POST',
          fields: {
            videoVisionProvider: 'videoVisionProvider',
            videoVisionApiKey: 'videoVisionApiKey',
            semanticVisionModel: 'semanticVisionModel',
          },
        },
      },
      {
        key: 'semanticVisionModel',
        label: 'Video vision model',
        type: 'select',
        group: 'Video understanding',
        defaultValue: 'google/gemini-3.6-flash',
        providerField: 'videoVisionProvider',
        defaultValueByProvider: {
          google: 'google/gemini-3.6-flash',
          vercel_ai_gateway: 'google/gemini-3.6-flash',
          openai: 'openai/gpt-4o-mini',
        },
        help: 'Required for every runtime. Only video-capable models for the selected provider are shown.',
        options: [
          {
            label: 'Gemini 3.6 Flash',
            value: 'google/gemini-3.6-flash',
            icon: '/icons/gemini.svg',
            description: 'Current Google multimodal model for video understanding.',
          },
          {
            label: 'Gemini 3.5 Flash',
            value: 'google/gemini-3.5-flash',
            icon: '/icons/gemini.svg',
            description: 'Fast video and image understanding.',
          },
          {
            label: 'GPT-4o mini',
            value: 'openai/gpt-4o-mini',
            icon: '/icons/openai.svg',
            description: 'Efficient OpenAI vision model.',
          },
        ],
      },
      {
        key: 'videoAgentProvider',
        label: 'Agent provider',
        type: 'select',
        group: 'Agent planning',
        defaultValue: 'vercel_ai_gateway',
        defaultFromGlobalConfigKey: 'chatProvider',
        help: 'Required for every runtime. Starts with your saved AI Models provider; this user-paid model plans and synthesizes evidence.',
        options: [
          {
            label: 'Google Gemini',
            value: 'google',
            icon: '/icons/gemini.svg',
            description: 'Use a Gemini model directly for extraction planning.',
          },
          {
            label: 'Vercel AI Gateway',
            value: 'vercel_ai_gateway',
            icon: '/icons/vercel.svg',
            description: 'Use any supported Gateway language model.',
          },
          {
            label: 'OpenAI',
            value: 'openai',
            icon: '/icons/openai.svg',
            description: 'Use an OpenAI model directly for extraction planning.',
          },
        ],
      },
      {
        key: 'videoAgentApiKey',
        label: 'Agent provider API key',
        type: 'password',
        group: 'Agent planning',
        help: 'Required unless this provider key is already saved in AI Models. It may differ from the vision key and is forwarded only for the active job.',
        verification: {
          endpoint: '/api/tools/video-intelligence/verify',
          method: 'POST',
          fields: {
            videoAgentProvider: 'videoAgentProvider',
            videoAgentApiKey: 'videoAgentApiKey',
            agentModel: 'agentModel',
          },
        },
      },
      {
        key: 'agentModel',
        label: 'Agent / tool-brain model',
        type: 'select',
        group: 'Agent planning',
        defaultValue: 'openai/gpt-5-mini',
        providerField: 'videoAgentProvider',
        defaultValueByProvider: {
          google: 'google/gemini-3.5-flash-lite',
          vercel_ai_gateway: 'openai/gpt-5-mini',
          openai: 'openai/gpt-5-mini',
        },
        help: 'Required for every runtime. This model plans modalities, segments, and extraction focus; the vision model reads frames.',
        options: [
          {
            label: 'Gemini 3.5 Flash Lite',
            value: 'google/gemini-3.5-flash-lite',
            icon: '/icons/gemini.svg',
            description: 'Low-latency planning for Fast and Balanced indexing.',
          },
          {
            label: 'Gemini 3.6 Flash',
            value: 'google/gemini-3.6-flash',
            icon: '/icons/gemini.svg',
            description: 'Stronger planning for complex source signals.',
          },
          {
            label: 'GPT-5 mini',
            value: 'openai/gpt-5-mini',
            icon: '/icons/openai.svg',
            description: 'Efficient structured planning with strong instruction following.',
          },
          {
            label: 'GPT-5.2',
            value: 'openai/gpt-5.2',
            icon: '/icons/openai.svg',
            description: 'Higher-accuracy planning for Thorough indexing.',
          },
        ],
      },
      {
        key: 'customRuntimeUrl',
        label: 'Custom runtime URL',
        type: 'text',
        group: 'Custom runtime',
        required: true,
        verification: {
          endpoint: '/api/tools/video-intelligence/verify',
          method: 'POST',
          fields: {
            customRuntimeUrl: 'customRuntimeUrl',
            customRuntimeApiKey: 'customRuntimeApiKey',
            runtimeMode: 'runtimeMode',
          },
        },
        visibleWhen: { field: 'runtimeMode', equals: 'custom-remote' },
      },
      {
        key: 'customRuntimeApiKey',
        label: 'Custom runtime API key',
        type: 'password',
        group: 'Custom runtime',
        required: true,
        visibleWhen: { field: 'runtimeMode', equals: 'custom-remote' },
      },
      {
        key: 'audioProvider',
        label: 'Audio provider',
        type: 'select',
        group: 'Audio',
        defaultValue: 'deepgram',
        help: 'Required for every runtime. Transcription is billed directly to your selected provider; Larkup Cloud does not supply audio-model credits.',
        options: [
          {
            label: 'OpenAI',
            value: 'openai',
            icon: '/icons/openai.svg',
            description: 'Use your OpenAI transcription allowance.',
          },
          {
            label: 'Groq',
            value: 'groq',
            icon: 'https://models.dev/logos/groq.svg',
            description: 'Fast hosted Whisper inference.',
          },
          {
            label: 'Deepgram',
            value: 'deepgram',
            icon: '/icons/deepgram.png',
            description: 'Speech-to-text with language features.',
          },
          {
            label: 'ElevenLabs',
            value: 'elevenlabs',
            icon: '/icons/elevenlabs.png',
            description: 'Use your ElevenLabs speech-to-text account.',
          },
        ],
      },
      {
        key: 'audioApiKey',
        label: 'Audio provider API key',
        type: 'password',
        group: 'Audio',
        help: 'Required. It stays in this installation and is forwarded only for the active video job.',
        verification: {
          endpoint: '/api/tools/video-intelligence/verify',
          method: 'POST',
          fields: {
            audioProvider: 'audioProvider',
            audioApiKey: 'audioApiKey',
            audioModel: 'audioModel',
          },
        },
        visibleWhen: {
          field: 'audioProvider',
          equals: ['openai', 'groq', 'deepgram', 'elevenlabs'],
        },
      },
      {
        key: 'audioModel',
        label: 'Audio transcription model',
        type: 'select',
        group: 'Audio',
        defaultValue: 'nova-3',
        providerField: 'audioProvider',
        defaultValueByProvider: {
          openai: 'whisper-1',
          groq: 'whisper-large-v3-turbo',
          deepgram: 'nova-3',
          elevenlabs: 'scribe_v2',
        },
        help: 'Required for every runtime. The model runs on your audio-provider account.',
        options: [
          { label: 'OpenAI Whisper 1', value: 'whisper-1', icon: '/icons/openai.svg' },
          {
            label: 'Groq Whisper Large v3 Turbo',
            value: 'whisper-large-v3-turbo',
            icon: 'https://models.dev/logos/groq.svg',
          },
          { label: 'Deepgram Nova 3', value: 'nova-3', icon: '/icons/deepgram.png' },
          {
            label: 'ElevenLabs Scribe v2',
            value: 'scribe_v2',
            icon: '/icons/elevenlabs.png',
          },
        ],
      },
      {
        key: 'cloudAccessKey',
        label: 'Larkup Cloud API key',
        type: 'password',
        group: 'Managed cloud connection',
        help: 'Paste the key Larkup provides for managed cloud access. Leave this empty only when automatic project provisioning is enabled.',
        visibleWhen: { field: 'runtimeMode', equals: 'managed-cloud' },
      },
      {
        key: 'defaultIndexingMode',
        label: 'Default indexing mode',
        type: 'select',
        group: 'Indexing',
        defaultValue: 'balanced',
        options: [
          { label: 'Fast', value: 'fast' },
          { label: 'Balanced', value: 'balanced' },
          { label: 'Thorough', value: 'thorough' },
        ],
      },
      {
        key: 'cloudInstallationId',
        label: 'Managed cloud installation ID',
        type: 'text',
        group: 'Managed cloud connection',
        help: 'Provisioned automatically for this project.',
        serverManaged: true,
      },
    ],
  },
  {
    id: 'clip-embeddings',
    name: 'CLIP Image Search',
    description: 'Direct image-to-image similarity search using CLIP/SigLIP embeddings.',
    longDescription:
      'Enable native visual similarity search by embedding images with CLIP or SigLIP models. ' +
      "Search your image library by uploading a query image or describing what you're looking for. " +
      'Requires downloading a ~200MB model on first use.',
    category: 'embedding',
    version: '0.1.0',
    pricing: 'free',
    emoji: '🔍',
    icon: 'ScanEye',
    packageName: '@larkup/tool-clip-embeddings',
    installSize: '~200 MB',
    author: 'Larkup',
    capabilities: ['clip-embeddings', 'image-similarity'],
    tags: ['clip', 'siglip', 'image-search', 'visual-similarity'],
    repositoryUrl: 'https://github.com/Larkup-AI/larkup',
    license: 'Apache-2.0',
    updatedAt: '2026-07-20',
    comingSoon: true,
  },
  {
    id: 'doc-editor',
    name: 'Document Editor',
    description: 'AI-powered form filling and document editing with Canvas-style live preview.',
    longDescription:
      'Open PDF, Word, PowerPoint, and text files in a split-view Canvas. ' +
      'AI fills forms using your knowledge base, edits content on request, and previews changes live. ' +
      'Supports PDF form fields (AcroForm), DOCX paragraphs/tables, PPTX slide text, and plain text editing. ' +
      'Uses pdf-lib (native) for PDF and the Docker sandbox for DOCX/PPTX via python-docx/python-pptx.',
    category: 'utility',
    version: '0.2.3',
    pricing: 'free',
    emoji: '📝',
    icon: 'FileEdit',
    packageName: '@larkup/tool-doc-editor',
    installSize: '~5 MB',
    systemDeps: ['docker'],
    requiresSandbox: true,
    author: 'Larkup',
    capabilities: ['document-editing', 'form-filling', 'document-preview'],
    tags: ['pdf', 'docx', 'pptx', 'form', 'canvas', 'editor', 'fill'],
    repositoryUrl: 'https://github.com/Larkup-AI/larkup',
    license: 'Apache-2.0',
    updatedAt: '2026-07-20',
  },
];
